volumes:
  gastroids2:
    external: true

services:
  api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://gastroids_user:password@db/gastroids_db
      WAIT_HOSTS: db:5432
      PORT: 8000
      SIGNING_KEY: 8661cc250e528b00007eb201f8a590db6147e12f44eb07fdcfb2b5a1c6324d8c
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: gastroids_user
      POSTGRES_DB: gastroids_db
    ports:
      - "15432:5432"
    volumes:
      - gastroids2:/var/lib/postgresql/data
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - gastroids2:/var/lib/postgresql/data
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: gastroids@gastroids.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
