# volumes:
#   gastroids2:
#     external: true
# services:
#   fastapi:
#     build:
#       context: ./fastapi
#       dockerfile: Dockerfile.dev
#     environment:
#       DATABASE_URL: postgresql://gastroids2:gastroids2@db/gastroids2
#       WAIT_HOSTS: db:5432
#       PORT: 8000
#     ports:
#       - 8000:80
#     volumes:
#       - ./fastapi:/app

#   postgres:
#     image: postgres:14.5-bullseye
#     environment:
#       POSTGRES_PASSWORD: gastroids2
#       POSTGRES_USER: gastroids2
#       POSTGRES_DB: gastroids2
#     ports:
#       - '15432:5432'
#     volumes:
#       - gastroids2:/var/lib/postgresql

#   ghi:
#     image: node:lts-bullseye
#     command: /bin/bash run.sh
#     working_dir: /app
#     volumes:
#       - ./ghi:/app
#     ports:
#       - '3000:3000'
#     environment:
#       HOST_OS: ${OS}
#       NODE_ENV: development
#       HOST: '0.0.0.0'
#       PUBLIC_URL: http://localhost:3000
#       REACT_APP_API_HOST: http://localhost:8000


volumes:
  gastroids2:
    external: true
services:
  api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://gastroids_user:password@db/gastroids_db
      WAIT_HOSTS: db:5432
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: gastroids_user
      POSTGRES_DB: gastroids_db
    ports:
      - "15432:5432"
    volumes:
      - gastroids2:/var/lib/postgresql/data

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - '3000:3000'
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: '0.0.0.0'
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000
